access_log /dev/stdout;

server {
	listen 8088 ssl http2;
	server_name nluchini.42.fr;

	ssl_certificate      /etc/nginx/ssl/nginx.crt;
	ssl_certificate_key  /etc/nginx/ssl/nginx.key;

	
	root /var/www/html;
    index index.nginx-debian.html;

	location / {
		try_files $uri $uri/ =404;
	}
}

server {
	listen 443 ssl http2;
	server_name localhost;

	ssl_certificate      /etc/nginx/ssl/nginx.crt;
	ssl_certificate_key  /etc/nginx/ssl/nginx.key;

	location / {
		proxy_pass http://wordpress:9000/;
		index  index.html index.htm;
	}

	location ~ \.php$ {
		fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $request_filename;
		include fastcgi_params;
	}
}