access_log /dev/stdout;

server {
	listen 443 ssl http2;
	server_name _;

	ssl_certificate      /etc/nginx/ssl/nginx.crt;
	ssl_certificate_key  /etc/nginx/ssl/nginx.key;

	root /var/www/html;
    index index.php index.html index.htm;

 
	location /adminer {
		fastcgi_pass adminer:9000;
		fastcgi_index index.php;
		include fastcgi_params;

		fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
	}

	location = /nik {
		return 301 https://nluchini.42.fr/nik/;
	}

	location /nik/ {
		proxy_pass http://my-syte:80/;
	}

	location = /grafana {
		return 301 https://nluchini.42.fr/grafana/;
	}

	location /grafana/ {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Prefix /grafana;
		proxy_pass http://grafana:3000;
	}

	location /grafana/api/live/ {
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Prefix /grafana;
		proxy_pass http://grafana:3000;
	}

	location / {
        try_files $uri $uri/ /index.php?$args;
    }

	location ~ \.php$ {
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}
}
