name: test

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: ngnix
    env_file:
      - path: ./.env
        required: true
    ports:
      - "8443:443"
    networks:
      - inseption
    depends_on:
      - wordpress
    secrets:
      - ngnix_crt
      - ngnix_key
    volumes:
      - ./requirements/nginx/conf/defualt.conf:/etc/nginx/conf.d/defualt.conf
      - web-data:/var/www/html

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - path: ./.env
        required: true
    secrets:
      - db_password
    networks:
      - inseption
    depends_on:
      - mariadb
    volumes:
      - ./requirements/wordpress/conf/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
      - web-data:/var/www/html


  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - path: ./.env
        required: true
    secrets:
      - db_password
      - db_admin_user
      - db_admin_password
    networks:
      - inseption
    volumes:
      - ./requirements/mariadb/conf/server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - data-base:/var/lib/mysql

networks:
  inseption:
    driver:
      "bridge"

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_admin_user:
    file: ./secrets/db_admin_user.txt
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  ngnix_crt:
    file: ./secrets/ssl/nginx.crt
  ngnix_key:
    file: ./secrets/ssl/nginx.key

volumes:
  web-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nluchini/data/
  data-base: