name: test

services:
  loki:
    build: ./requirements/bonus/loki
    container_name: loki
    volumes:
      - loki-data:/loki
    ports:
      - "3100:3100"
    restart: unless-stopped

  dozzle:
    build: ./requirements/bonus/dozzle
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    restart: unless-stopped


  ftp-service:
    build:
      context: ./bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    restart: on-failure:5
    networks:
      - inseption
    volumes:
      - ./bonus/ftp/conf/vsftpd.conf:/etc/vsftpd.conf
      - web-data:/var/www/html
    ports:
      - "4321:21"
      - "60000-60005:60000-60005"
    env_file:
      - path: ./env/.env
        required: true
    secrets:
      - ftp_password


  my-syte:
    build:
      context: ./bonus/static-website
      dockerfile: Dockerfile
    container_name: my-syte
    restart: on-failure:5
    networks:
      - inseption
    volumes:
      - ./bonus/static-website/conf/Caddyfile:/etc/caddy/Caddyfile
      - ./bonus/static-website/static-files:/var/www/html

  adminer:
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    restart: on-failure:5    
    networks:
      - inseption
    volumes:
      - ./bonus/adminer/conf/www.conf:/etc/php/8.2/fpm/pool.d/www.conf

  redis:
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: on-failure:5 
    networks:
      - inseption
    volumes:
      - ./bonus/redis/conf/redis.conf:/etc/redis/redis.conf
      - redis-data:/data

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: ngnix
    env_file:
      - path: ./env/.env
        required: true
    ports:
      - "8443:443"
    restart: on-failure:5
    networks:
      - inseption
    depends_on:
      - wordpress
    secrets:
      - ngnix_crt
      - ngnix_key
    volumes:
      - ./requirements/nginx/conf/defualt.conf:/etc/nginx/conf.d/defualt.conf
      - web-data:/var/www/html

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - path: ./env/.env
        required: true
    secrets:
      - db_password
    restart: on-failure:5
    networks:
      - inseption
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./requirements/wordpress/conf/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
      - web-data:/var/www/html


  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - path: ./env/.env
        required: true
    secrets:
      - db_password
      - db_admin_password
    restart: on-failure:5
    networks:
      - inseption
    volumes:
      - ./requirements/mariadb/conf/server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - data-base:/var/lib/mysql

networks:
  inseption:
    driver:
      "bridge"

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  ngnix_crt:
    file: ./secrets/ssl/nginx.crt
  ngnix_key:
    file: ./secrets/ssl/nginx.key
  ftp_password:
    file: ./secrets/ftp_passwor.txt

volumes:
  web-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nluchini/data/	
  data-base:
    name: data-base
  redis-data:
    name: redis-data
  portainer_data:
    name: portainer_data
  loki-data:
    name: loki-data  
