name: test

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: ngnix
    environment:
      - NGNIX_CRT_FILE=/run/secrets/ngnix_crt
      - NGNIX_KEY_FILE=/run/secrets/ngnix_key
    ports:
      - "8443:443"
      - "8088:8088"
    networks:
      - inseption
    depends_on:
      - wordpress
    secrets:
      - ngnix_crt
      - ngnix_key

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    environment:
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_HOST=mariadb
    secrets:
      - db_password
    networks:
      - inseption
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_ADMIN_USER_FILE=/run/secrets/db_admin_user
      - DB_ADMIN_PASSWORD_FILE=/run/secrets/db_admin_password
    secrets:
      - db_password
      - db_admin_user
      - db_admin_password
    networks:
      - inseption

networks:
  inseption:
    driver:
      "bridge"

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_admin_user:
    file: ./secrets/db_admin_user.txt
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  ngnix_crt:
    file: ./secrets/ssl/nginx.crt
  ngnix_key:
    file: ./secrets/ssl/nginx.key