# OpenSSL configuration file for creating a CSR for a server certificate

# the fully qualified server (or service) name
FQDN = example.42.fr
#https://10.12.3.3:8088

# the name of your organization
# (see also https://www.switch.ch/pki/participants/)
ORGNAME = example

# subjectAltName entries: to add DNS aliases to the CSR, delete
# the '#' character in the ALTNAMES line, and change the subsequent
# 'DNS:' entries accordingly. Please note: all DNS names must
# resolve to the same IP address as the FQDN.
ALTNAMES = DNS:$FQDN,DNS:localhost,IP:127.0.0.1

# --- no modifications required below ---
[ req ]
default_bits = 2048
default_md = sha256
prompt = no
distinguished_name = req_dn 
x509_extensions = x509_ext
encrypt_key = no
req_extensions = req_ext

[ req_dn ]
C = DE
O = some-organization
CN = $FQDN

[ req_ext ]
subjectAltName = $ALTNAMES

[ x509_ext ]
subjectAltName = $ALTNAMES